global_costmap:
  global_frame: map
  robot_base_frame: odom 
  update_frequency: 2.0
  publish_frequency: 2.0
  resolution: 0.05
  static_map: false
  rolling_window: true
  transform_tolerance: 1.0 
  cost_scaling_factor: 5.0
  infration_radius: 0.10
  width: 10.0
  height: 10.0
